name:                autotool-task-test
version:             0.1.0.0
license:             BSD3
author:              "Oliver Westphal"
maintainer:          "oliver.westphal <at> uni-due.de"
copyright:           "2020 Oliver Westphal"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fmidue/autotool-task-test#readme>

dependencies:
- base >= 4.12 && < 5
- ghc == 9.4.5
- ghc-paths
- ghc-boot-th
- directory
- extra
- haskell-template-task-raw
- HUnit

ghc-options:
- -Wall

executables:
  test-task:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - random
      - syb
      - haskell-src-exts
      - haskell-template-task-embedded # used for run-time compilation dependencies

  pkg-path-from-stack:
    main: Main.hs
    source-dirs: app/pkg-path
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - process
