resolver: nightly-2023-05-11

packages:
- .

extra-deps:
  - hint-0.9.0.6
  - git: https://github.com/fmidue/haskell-template-task
    commit: 6b714ff8e49afb2e28a5ddeadb3aeebb6ec33c97
    subdirs:
      - raw
      - raw/embedded

  - git: https://github.com/owestphal/mini-IOTasks
    commit: 0b93dfed553a027b69aa7ba26d559a3bb77179a1

  - git: https://github.com/IagoAbal/haskell-z3
    commit: 7e2a3e0977f277b9ed39ad182287317d2b819476

  - express-1.0.8@sha256:02d6e556befd3fa072600305202e7eda9b54f37b7c8aa84a2f874b1a646474d1,11062
allow-newer: true

compiler-check:
  newer-minor
