resolver: nightly-2023-04-24

packages:
- .

extra-deps:
  - hint-0.9.0.6
  - git: https://github.com/fmidue/haskell-template-task
    commit: 1192e9780c0d3a0222f2b93a464acba701c40ee4
    subdirs:
      - raw
      - raw/embedded

  - git: https://github.com/owestphal/mini-IOTasks
    commit: 5bdc9c76cb8901b40d53084d2709e8ab1c356225

  - git: https://github.com/owestphal/type-match
    commit: e5c0d104032d7e6ea147009669cbb95f3291b7bb

  - git: https://github.com/IagoAbal/haskell-z3
    commit: 6368e451e45359563106da7e917f6594453c5161

  - express-1.0.8@sha256:02d6e556befd3fa072600305202e7eda9b54f37b7c8aa84a2f874b1a646474d1,11062

  - codeworld-api-0.8.1
  - patch-0.0.8.1
  - reflex-0.9.0.0

compiler-check:
  match-exact

allow-newer: true
allow-newer-deps:
  - reflex
